<?php
/*
Section of paging
*********************************************************************************************************/
$PageSize = 15;
$PageNo = (isset($_GET['PageNo'])?$_GET['PageNo']:0);
$Pagenumber = 10;
$ModePaging = "Full";
/*Setting language
*******************************************************************************************************/
/*$arraySMTPSERVER = array("host" => "sv7362.xserver.jp", "user" => "info@demoetrust.xsrv.jp", "password" => "m{Q]EI+qNZmD", "from" => "NEONAGASHIMA");*/
/*$arraySMTPSERVER = array("host" => "neonaga-sys.com.vn", "user" => "lienhe@neonaga-sys.com.vn", "password" => "oS?naRS-3cS,", "from" => "VietQuocLab");*/ 
$arraySMTPSERVER = array("host" => "sv7362.xserver.jp", "user" => "info@vietquoclab.com", "password" => "Vietquoc123", "from" => "VietQuocLab");
$next1 = "<b>&nbsp;&rsaquo;&nbsp;</b>";
$next2 = "<b>&nbsp;&rsaquo;&rsaquo;&nbsp;</b>";

define("prefixTable", "");
define("HOST", "http://" . $_SERVER["HTTP_HOST"] . "/");
define("HOSTS", "https://" . $_SERVER["HTTP_HOST"] . "/");
define ("MIN_INT",10000000);
define ("MAX_INT",99999999);
define("THEMES_NAME", "");
define("ROOT_URLPATH", "/");
define("DOMAIN_NAME", $_SERVER["HTTP_HOST"]);
define("COOKIE_EXPIRE", 365);
define("PERPAGE_LIMIT",10);

/*
*******************************************************************************************************/
$URL_GOC = explode(".aspx", $_SERVER["REQUEST_URI"]);
if (count($URL_GOC) > 0) {
  $URL = explode("/", $URL_GOC[0]);
}
else {
  $URL = explode("/", $_SERVER["REQUEST_URI"]);
}
array_shift($URL);
$page = strtolower($URL[0]);
if ($page == '') {
  $page = 'home';
}
if (empty($page))
  $page = "home";
$country_code = ['JP' => ['name' => 'Japan', 'dial_code' => '+81'],
'VN' => ['name' => 'Viet Nam', 'dial_code' => '+84'],
'IL' => ['name' => 'Israel', 'dial_code' => '+972'],
'AF' => ['name' => 'Afghanistan', 'dial_code' => '+93'],
'AL' => ['name' => 'Albania', 'dial_code' => '+355'],
'DZ' => ['name' => 'Algeria', 'dial_code' => '+213'],
'AS' => ['name' => 'AmericanSamoa', 'dial_code' => '+1 684'],
'AD' => ['name' => 'Andorra', 'dial_code' => '+376'],
'AO' => ['name' => 'Angola', 'dial_code' => '+244'],
'AI' => ['name' => 'Anguilla', 'dial_code' => '+1 264'],
'AG' => ['name' => 'Antigua and Barbuda', 'dial_code' => '+1268'],
'AR' => ['name' => 'Argentina', 'dial_code' => '+54'],
'AM' => ['name' => 'Armenia', 'dial_code' => '+374'],
'AW' => ['name' => 'Aruba', 'dial_code' => '+297'],
'AU' => ['name' => 'Australia', 'dial_code' => '+61'],
'AT' => ['name' => 'Austria', 'dial_code' => '+43'],
'AZ' => ['name' => 'Azerbaijan', 'dial_code' => '+994'],
'BS' => ['name' => 'Bahamas', 'dial_code' => '+1 242'],
'BH' => ['name' => 'Bahrain', 'dial_code' => '+973'],
'BD' => ['name' => 'Bangladesh', 'dial_code' => '+880'],
'BB' => ['name' => 'Barbados', 'dial_code' => '+1 246'],
'BY' => ['name' => 'Belarus', 'dial_code' => '+375'],
'BE' => ['name' => 'Belgium', 'dial_code' => '+32'],
'BZ' => ['name' => 'Belize', 'dial_code' => '+501'],
'BJ' => ['name' => 'Benin', 'dial_code' => '+229'],
'BM' => ['name' => 'Bermuda', 'dial_code' => '+1 441'],
'BT' => ['name' => 'Bhutan', 'dial_code' => '+975'],
'BA' => ['name' => 'Bosnia and Herzegovina', 'dial_code' => '+387'],
'BW' => ['name' => 'Botswana', 'dial_code' => '+267'],
'BR' => ['name' => 'Brazil', 'dial_code' => '+55'],
'IO' => ['name' => 'British Indian Ocean Territory', 'dial_code' => '+246'],
'BG' => ['name' => 'Bulgaria', 'dial_code' => '+359'],
'BF' => ['name' => 'Burkina Faso', 'dial_code' => '+226'],
'BI' => ['name' => 'Burundi', 'dial_code' => '+257'],
'KH' => ['name' => 'Cambodia', 'dial_code' => '+855'],
'CM' => ['name' => 'Cameroon', 'dial_code' => '+237'],
'CA' => ['name' => 'Canada', 'dial_code' => '+1'],
'CV' => ['name' => 'Cape Verde', 'dial_code' => '+238'],
'KY' => ['name' => 'Cayman Islands', 'dial_code' => '+ 345'],
'CF' => ['name' => 'Central African Republic', 'dial_code' => '+236'],
'TD' => ['name' => 'Chad', 'dial_code' => '+235'],
'CL' => ['name' => 'Chile', 'dial_code' => '+56'],
'CN' => ['name' => 'China', 'dial_code' => '+86'],
'CX' => ['name' => 'Christmas Island', 'dial_code' => '+61'],
'CO' => ['name' => 'Colombia', 'dial_code' => '+57'],
'KM' => ['name' => 'Comoros', 'dial_code' => '+269'],
'CG' => ['name' => 'Congo', 'dial_code' => '+242'],
'CK' => ['name' => 'Cook Islands', 'dial_code' => '+682'],
'CR' => ['name' => 'Costa Rica', 'dial_code' => '+506'],
'HR' => ['name' => 'Croatia', 'dial_code' => '+385'],
'CU' => ['name' => 'Cuba', 'dial_code' => '+53'],
'CY' => ['name' => 'Cyprus', 'dial_code' => '+537'],
'CZ' => ['name' => 'Czech Republic', 'dial_code' => '+420'],
'DK' => ['name' => 'Denmark', 'dial_code' => '+45'],
'DJ' => ['name' => 'Djibouti', 'dial_code' => '+253'],
'DM' => ['name' => 'Dominica', 'dial_code' => '+1 767'],
'DO' => ['name' => 'Dominican Republic', 'dial_code' => '+1 849'],
'EC' => ['name' => 'Ecuador', 'dial_code' => '+593'],
'EG' => ['name' => 'Egypt', 'dial_code' => '+20'],
'SV' => ['name' => 'El Salvador', 'dial_code' => '+503'],
'GQ' => ['name' => 'Equatorial Guinea', 'dial_code' => '+240'],
'ER' => ['name' => 'Eritrea', 'dial_code' => '+291'],
'EE' => ['name' => 'Estonia', 'dial_code' => '+372'],
'ET' => ['name' => 'Ethiopia', 'dial_code' => '+251'],
'FO' => ['name' => 'Faroe Islands', 'dial_code' => '+298'],
'FJ' => ['name' => 'Fiji', 'dial_code' => '+679'],
'FI' => ['name' => 'Finland', 'dial_code' => '+358'],
'FR' => ['name' => 'France', 'dial_code' => '+33'],
'GF' => ['name' => 'French Guiana', 'dial_code' => '+594'],
'PF' => ['name' => 'French Polynesia', 'dial_code' => '+689'],
'GA' => ['name' => 'Gabon', 'dial_code' => '+241'],
'GM' => ['name' => 'Gambia', 'dial_code' => '+220'],
'GE' => ['name' => 'Georgia', 'dial_code' => '+995'],
'DE' => ['name' => 'Germany', 'dial_code' => '+49'],
'GH' => ['name' => 'Ghana', 'dial_code' => '+233'],
'GI' => ['name' => 'Gibraltar', 'dial_code' => '+350'],
'GR' => ['name' => 'Greece', 'dial_code' => '+30'],
'GL' => ['name' => 'Greenland', 'dial_code' => '+299'],
'GD' => ['name' => 'Grenada', 'dial_code' => '+1 473'],
'GP' => ['name' => 'Guadeloupe', 'dial_code' => '+590'],
'GU' => ['name' => 'Guam', 'dial_code' => '+1 671'],
'GT' => ['name' => 'Guatemala', 'dial_code' => '+502'],
'GN' => ['name' => 'Guinea', 'dial_code' => '+224'],
'GW' => ['name' => 'Guinea-Bissau', 'dial_code' => '+245'],
'GY' => ['name' => 'Guyana', 'dial_code' => '+595'],
'HT' => ['name' => 'Haiti', 'dial_code' => '+509'],
'HN' => ['name' => 'Honduras', 'dial_code' => '+504'],
'HU' => ['name' => 'Hungary', 'dial_code' => '+36'],
'IS' => ['name' => 'Iceland', 'dial_code' => '+354'],
'IN' => ['name' => 'India', 'dial_code' => '+91'],
'ID' => ['name' => 'Indonesia', 'dial_code' => '+62'],
'IQ' => ['name' => 'Iraq', 'dial_code' => '+964'],
'IE' => ['name' => 'Ireland', 'dial_code' => '+353'],
'IL' => ['name' => 'Israel', 'dial_code' => '+972'],
'IT' => ['name' => 'Italy', 'dial_code' => '+39'],
'JM' => ['name' => 'Jamaica', 'dial_code' => '+1 876'],
'JO' => ['name' => 'Jordan', 'dial_code' => '+962'],
'KZ' => ['name' => 'Kazakhstan', 'dial_code' => '+7 7'],
'KE' => ['name' => 'Kenya', 'dial_code' => '+254'],
'KI' => ['name' => 'Kiribati', 'dial_code' => '+686'],
'KW' => ['name' => 'Kuwait', 'dial_code' => '+965'],
'KG' => ['name' => 'Kyrgyzstan', 'dial_code' => '+996'],
'LV' => ['name' => 'Latvia', 'dial_code' => '+371'],
'LB' => ['name' => 'Lebanon', 'dial_code' => '+961'],
'LS' => ['name' => 'Lesotho', 'dial_code' => '+266'],
'LR' => ['name' => 'Liberia', 'dial_code' => '+231'],
'LI' => ['name' => 'Liechtenstein', 'dial_code' => '+423'],
'LT' => ['name' => 'Lithuania', 'dial_code' => '+370'],
'LU' => ['name' => 'Luxembourg', 'dial_code' => '+352'],
'MG' => ['name' => 'Madagascar', 'dial_code' => '+261'],
'MW' => ['name' => 'Malawi', 'dial_code' => '+265'],
'MY' => ['name' => 'Malaysia', 'dial_code' => '+60'],
'MV' => ['name' => 'Maldives', 'dial_code' => '+960'],
'ML' => ['name' => 'Mali', 'dial_code' => '+223'],
'MT' => ['name' => 'Malta', 'dial_code' => '+356'],
'MH' => ['name' => 'Marshall Islands', 'dial_code' => '+692'],
'MQ' => ['name' => 'Martinique', 'dial_code' => '+596'],
'MR' => ['name' => 'Mauritania', 'dial_code' => '+222'],
'MU' => ['name' => 'Mauritius', 'dial_code' => '+230'],
'YT' => ['name' => 'Mayotte', 'dial_code' => '+262'],
'MX' => ['name' => 'Mexico', 'dial_code' => '+52'],
'MC' => ['name' => 'Monaco', 'dial_code' => '+377'],
'MN' => ['name' => 'Mongolia', 'dial_code' => '+976'],
'ME' => ['name' => 'Montenegro', 'dial_code' => '+382'],
'MS' => ['name' => 'Montserrat', 'dial_code' => '+1664'],
'MA' => ['name' => 'Morocco', 'dial_code' => '+212'],
'MM' => ['name' => 'Myanmar', 'dial_code' => '+95'],
'NA' => ['name' => 'Namibia', 'dial_code' => '+264'],
'NR' => ['name' => 'Nauru', 'dial_code' => '+674'],
'NP' => ['name' => 'Nepal', 'dial_code' => '+977'],
'NL' => ['name' => 'Netherlands', 'dial_code' => '+31'],
'AN' => ['name' => 'Netherlands Antilles', 'dial_code' => '+599'],
'NC' => ['name' => 'New Caledonia', 'dial_code' => '+687'],
'NZ' => ['name' => 'New Zealand', 'dial_code' => '+64'],
'NI' => ['name' => 'Nicaragua', 'dial_code' => '+505'],
'NE' => ['name' => 'Niger', 'dial_code' => '+227'],
'NG' => ['name' => 'Nigeria', 'dial_code' => '+234'],
'NU' => ['name' => 'Niue', 'dial_code' => '+683'],
'NF' => ['name' => 'Norfolk Island', 'dial_code' => '+672'],
'MP' => ['name' => 'Northern Mariana Islands', 'dial_code' => '+1 670'],
'NO' => ['name' => 'Norway', 'dial_code' => '+47'],
'OM' => ['name' => 'Oman', 'dial_code' => '+968'],
'PK' => ['name' => 'Pakistan', 'dial_code' => '+92'],
'PW' => ['name' => 'Palau', 'dial_code' => '+680'],
'PA' => ['name' => 'Panama', 'dial_code' => '+507'],
'PG' => ['name' => 'Papua New Guinea', 'dial_code' => '+675'],
'PY' => ['name' => 'Paraguay', 'dial_code' => '+595'],
'PE' => ['name' => 'Peru', 'dial_code' => '+51'],
'PH' => ['name' => 'Philippines', 'dial_code' => '+63'],
'PL' => ['name' => 'Poland', 'dial_code' => '+48'],
'PT' => ['name' => 'Portugal', 'dial_code' => '+351'],
'PR' => ['name' => 'Puerto Rico', 'dial_code' => '+1 939'],
'QA' => ['name' => 'Qatar', 'dial_code' => '+974'],
'RO' => ['name' => 'Romania', 'dial_code' => '+40'],
'RW' => ['name' => 'Rwanda', 'dial_code' => '+250'],
'WS' => ['name' => 'Samoa', 'dial_code' => '+685'],
'SM' => ['name' => 'San Marino', 'dial_code' => '+378'],
'SA' => ['name' => 'Saudi Arabia', 'dial_code' => '+966'],
'SN' => ['name' => 'Senegal', 'dial_code' => '+221'],
'RS' => ['name' => 'Serbia', 'dial_code' => '+381'],
'SC' => ['name' => 'Seychelles', 'dial_code' => '+248'],
'SL' => ['name' => 'Sierra Leone', 'dial_code' => '+232'],
'SG' => ['name' => 'Singapore', 'dial_code' => '+65'],
'SK' => ['name' => 'Slovakia', 'dial_code' => '+421'],
'SI' => ['name' => 'Slovenia', 'dial_code' => '+386'],
'SB' => ['name' => 'Solomon Islands', 'dial_code' => '+677'],
'ZA' => ['name' => 'South Africa', 'dial_code' => '+27'],
'GS' => ['name' => 'South Georgia and the South Sandwich Islands', 'dial_code' => '+500'],
'ES' => ['name' => 'Spain', 'dial_code' => '+34'],
'LK' => ['name' => 'Sri Lanka', 'dial_code' => '+94'],
'SD' => ['name' => 'Sudan', 'dial_code' => '+249'],
'SR' => ['name' => 'Suriname', 'dial_code' => '+597'],
'SZ' => ['name' => 'Swaziland', 'dial_code' => '+268'],
'SE' => ['name' => 'Sweden', 'dial_code' => '+46'],
'CH' => ['name' => 'Switzerland', 'dial_code' => '+41'],
'TJ' => ['name' => 'Tajikistan', 'dial_code' => '+992'],
'TH' => ['name' => 'Thailand', 'dial_code' => '+66'],
'TG' => ['name' => 'Togo', 'dial_code' => '+228'],
'TK' => ['name' => 'Tokelau', 'dial_code' => '+690'],
'TO' => ['name' => 'Tonga', 'dial_code' => '+676'],
'TT' => ['name' => 'Trinidad and Tobago', 'dial_code' => '+1 868'],
'TN' => ['name' => 'Tunisia', 'dial_code' => '+216'],
'TR' => ['name' => 'Turkey', 'dial_code' => '+90'],
'TM' => ['name' => 'Turkmenistan', 'dial_code' => '+993'],
'TC' => ['name' => 'Turks and Caicos Islands', 'dial_code' => '+1 649'],
'TV' => ['name' => 'Tuvalu', 'dial_code' => '+688'],
'UG' => ['name' => 'Uganda', 'dial_code' => '+256'],
'UA' => ['name' => 'Ukraine', 'dial_code' => '+380'],
'AE' => ['name' => 'United Arab Emirates', 'dial_code' => '+971'],
'GB' => ['name' => 'United Kingdom', 'dial_code' => '+44'],
'US' => ['name' => 'United States', 'dial_code' => '+1'],
'UY' => ['name' => 'Uruguay', 'dial_code' => '+598'],
'UZ' => ['name' => 'Uzbekistan', 'dial_code' => '+998'],
'VU' => ['name' => 'Vanuatu', 'dial_code' => '+678'],
'WF' => ['name' => 'Wallis and Futuna', 'dial_code' => '+681'],
'YE' => ['name' => 'Yemen', 'dial_code' => '+967'],
'ZM' => ['name' => 'Zambia', 'dial_code' => '+260'],
'ZW' => ['name' => 'Zimbabwe', 'dial_code' => '+263'],
'AX' => ['name' => 'land Islands', 'dial_code' => ''],
'AQ' => ['name' => 'Antarctica', 'dial_code' => ''],
'BO' => ['name' => 'Bolivia, Plurinational State of', 'dial_code' => '+591'],
'BN' => ['name' => 'Brunei Darussalam', 'dial_code' => '+673'],
'CC' => ['name' => 'Cocos (Keeling) Islands', 'dial_code' => '+61'],
'CD' => ['name' => 'Congo, The Democratic Republic of the', 'dial_code' => '+243'],
'CI' => ['name' => 'Cote dIvoire', 'dial_code' => '+225'],
'FK' => ['name' => 'Falkland Islands (Malvinas)', 'dial_code' => '+500'],
'GG' => ['name' => 'Guernsey', 'dial_code' => '+44'],
'VA' => ['name' => 'Holy See (Vatican City State)', 'dial_code' => '+379'],
'HK' => ['name' => 'Hong Kong', 'dial_code' => '+852'],
'IR' => ['name' => 'Iran, Islamic Republic of', 'dial_code' => '+98'],
'IM' => ['name' => 'Isle of Man', 'dial_code' => '+44'],
'JE' => ['name' => 'Jersey', 'dial_code' => '+44'],
'KP' => ['name' => 'Korea, Democratic Peoples Republic of', 'dial_code' => '+850'],
'KR' => ['name' => 'Korea, Republic of', 'dial_code' => '+82'],
'LA' => ['name' => 'Lao Peoples Democratic Republic', 'dial_code' => '+856'],
'LY' => ['name' => 'Libyan Arab Jamahiriya', 'dial_code' => '+218'],
'MO' => ['name' => 'Macao', 'dial_code' => '+853'],
'MK' => ['name' => 'Macedonia, The Former Yugoslav Republic of', 'dial_code' => '+389'],
'FM' => ['name' => 'Micronesia, Federated States of', 'dial_code' => '+691'],
'MD' => ['name' => 'Moldova, Republic of', 'dial_code' => '+373'],
'MZ' => ['name' => 'Mozambique', 'dial_code' => '+258'],
'PS' => ['name' => 'Palestinian Territory, Occupied', 'dial_code' => '+970'],
'PN' => ['name' => 'Pitcairn', 'dial_code' => '+872'],
'RE' => ['name' => 'Réunion', 'dial_code' => '+262'],
'RU' => ['name' => 'Russia', 'dial_code' => '+7'],
'BL' => ['name' => 'Saint Barthélemy', 'dial_code' => '+590'],
'SH' => ['name' => 'Saint Helena, Ascension and Tristan Da Cunha', 'dial_code' => '+290'],
'KN' => ['name' => 'Saint Kitts and Nevis', 'dial_code' => '+1 869'],
'LC' => ['name' => 'Saint Lucia', 'dial_code' => '+1 758'],
'MF' => ['name' => 'Saint Martin', 'dial_code' => '+590'],
'PM' => ['name' => 'Saint Pierre and Miquelon', 'dial_code' => '+508'],
'VC' => ['name' => 'Saint Vincent and the Grenadines', 'dial_code' => '+1 784'],
'ST' => ['name' => 'Sao Tome and Principe', 'dial_code' => '+239'],
'SO' => ['name' => 'Somalia', 'dial_code' => '+252'],
'SJ' => ['name' => 'Svalbard and Jan Mayen', 'dial_code' => '+47'],
'SY' => ['name' => 'Syrian Arab Republic', 'dial_code' => '+963'],
'TW' => ['name' => 'Taiwan, Province of China', 'dial_code' => '+886'],
'TZ' => ['name' => 'Tanzania, United Republic of', 'dial_code' => '+255'],
'TL' => ['name' => 'Timor-Leste', 'dial_code' => '+670'],
'VE' => ['name' => 'Venezuela, Bolivarian Republic of', 'dial_code' => '+58'],
'VG' => ['name' => 'Virgin Islands, British', 'dial_code' => '+1 284'],
'VI' => ['name' => 'Virgin Islands, U.S.', 'dial_code' => '+1 340']];
?>